import SwiftUI

// Weekly schedule view: shows each day's visit list for the current saved schedule.
// The schedule is generated by the web app and stored in workspace.lastSchedule.

struct ScheduleView: View {
    @Environment(AppState.self) private var appState
    @State private var selectedDay: DayOfWeek?

    private var schedule: WeekSchedule? { appState.workspace?.lastSchedule }
    private var clients: [String: Client] {
        Dictionary(uniqueKeysWithValues: (appState.workspace?.clients ?? []).map { ($0.id, $0) })
    }

    var body: some View {
        NavigationStack {
            Group {
                if let schedule {
                    scheduleContent(schedule)
                } else {
                    emptyState
                }
            }
            .navigationTitle("Schedule")
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    if appState.isSyncing {
                        ProgressView().scaleEffect(0.8)
                    } else {
                        Button { Task { await appState.refreshWorkspace() } } label: {
                            Image(systemName: "arrow.clockwise")
                        }
                    }
                }
            }
        }
    }

    // MARK: - Schedule content

    private func scheduleContent(_ schedule: WeekSchedule) -> some View {
        VStack(spacing: 0) {
            // Week summary header
            weekSummary(schedule)

            // Unmet visits warning
            if let unmet = schedule.unmetVisits, !unmet.isEmpty {
                unmetBanner(unmet)
            }

            // Day selector tabs
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 8) {
                    ForEach(schedule.days) { day in
                        DayTab(
                            day: day,
                            isSelected: selectedDay == day.day,
                            hasVisits: !day.visits.isEmpty
                        ) {
                            selectedDay = day.day
                        }
                    }
                }
                .padding(.horizontal)
                .padding(.vertical, 8)
            }
            .background(Color(.secondarySystemBackground))

            Divider()

            // Selected day detail
            if let daySchedule = schedule.days.first(where: { $0.day == (selectedDay ?? firstActiveDay(schedule)) }) {
                DayDetailView(day: daySchedule, clients: clients)
            }
        }
        .onAppear {
            if selectedDay == nil { selectedDay = firstActiveDay(schedule) }
        }
    }

    // MARK: - Week summary

    private func weekSummary(_ schedule: WeekSchedule) -> some View {
        let days = schedule.days.filter { !$0.visits.isEmpty }
        let totalVisits = schedule.days.reduce(0) { $0 + $1.visits.count }

        return HStack(spacing: 16) {
            summaryCell(value: "\(days.count)", label: "Work days")
            summaryCell(value: "\(totalVisits)", label: "Visits")
            summaryCell(
                value: formatMinutes(schedule.totalTravelMinutes),
                label: "Driving"
            )
            summaryCell(
                value: formatMinutes(schedule.totalTimeAwayMinutes),
                label: "Away"
            )
        }
        .padding()
        .background(Color(.systemBackground))
    }

    private func summaryCell(value: String, label: String) -> some View {
        VStack(spacing: 2) {
            Text(value)
                .font(.headline)
            Text(label)
                .font(.caption2)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity)
    }

    // MARK: - Unmet visits warning

    private func unmetBanner(_ unmet: [UnmetVisit]) -> some View {
        let names = unmet.compactMap { uv in
            (appState.workspace?.clients.first { $0.id == uv.clientId })?.name
        }
        return Label(
            "Could not place all visits: \(names.joined(separator: ", "))",
            systemImage: "exclamationmark.triangle.fill"
        )
        .font(.caption)
        .foregroundStyle(.orange)
        .padding(.horizontal)
        .padding(.vertical, 8)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.orange.opacity(0.1))
    }

    // MARK: - Empty state

    private var emptyState: some View {
        VStack(spacing: 16) {
            Image(systemName: "calendar.badge.exclamationmark")
                .font(.system(size: 52))
                .foregroundStyle(.tertiary)
            Text("No schedule yet")
                .font(.headline)
            Text("Generate a schedule in the web app, then come back here.")
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 40)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // MARK: - Helpers

    private func firstActiveDay(_ schedule: WeekSchedule) -> DayOfWeek {
        schedule.days.first { !$0.visits.isEmpty }?.day ?? schedule.days.first?.day ?? .monday
    }

    private func formatMinutes(_ mins: Int) -> String {
        if mins < 60 { return "\(mins)m" }
        let h = mins / 60, m = mins % 60
        return m == 0 ? "\(h)h" : "\(h)h \(m)m"
    }
}

// MARK: - Day tab button

struct DayTab: View {
    let day: DaySchedule
    let isSelected: Bool
    let hasVisits: Bool
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            VStack(spacing: 2) {
                Text(day.day.label)
                    .font(.caption.weight(.semibold))
                Text("\(day.visits.count)")
                    .font(.caption2)
                    .foregroundStyle(hasVisits ? .primary : .tertiary)
            }
            .padding(.horizontal, 14)
            .padding(.vertical, 8)
            .background(isSelected ? Color.blue : Color.clear)
            .foregroundStyle(isSelected ? .white : (hasVisits ? .primary : .secondary))
            .clipShape(RoundedRectangle(cornerRadius: 8))
        }
        .buttonStyle(.plain)
    }
}

// MARK: - Day detail

struct DayDetailView: View {
    let day: DaySchedule
    let clients: [String: Client]

    var body: some View {
        if day.visits.isEmpty {
            VStack(spacing: 12) {
                Image(systemName: "bed.double")
                    .font(.system(size: 36))
                    .foregroundStyle(.tertiary)
                Text("Day off")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
        } else {
            ScrollView {
                VStack(alignment: .leading, spacing: 0) {
                    // Day header
                    HStack {
                        VStack(alignment: .leading, spacing: 2) {
                            Text(formatDate(day.date))
                                .font(.subheadline.weight(.medium))
                            HStack(spacing: 12) {
                                Label("Depart \(day.leaveHomeTime.formatted12h)", systemImage: "house.fill")
                                Label("Return \(day.arriveHomeTime.formatted12h)", systemImage: "house.fill")
                            }
                            .font(.caption)
                            .foregroundStyle(.secondary)
                        }
                        Spacer()
                        Label("\(day.visits.count) visits", systemImage: "person.2")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    .padding()

                    Divider()

                    // Visit timeline
                    LazyVStack(spacing: 0) {
                        ForEach(Array(day.visits.enumerated()), id: \.offset) { idx, visit in
                            ScheduleVisitRow(
                                visit: visit,
                                client: clients[visit.clientId],
                                isLast: idx == day.visits.count - 1
                            )
                        }
                    }
                    .padding(.horizontal)
                    .padding(.bottom, 24)
                }
            }
        }
    }

    private func formatDate(_ iso: String) -> String {
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd"
        fmt.locale = Locale(identifier: "en_US_POSIX")
        guard let d = fmt.date(from: iso) else { return iso }
        let out = DateFormatter()
        out.dateFormat = "EEEE, MMMM d"
        return out.string(from: d)
    }
}

// MARK: - Schedule visit row (compact timeline style)

struct ScheduleVisitRow: View {
    let visit: ScheduledVisit
    let client: Client?
    let isLast: Bool

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            // Timeline spine
            VStack(spacing: 0) {
                Circle()
                    .fill(Color.blue)
                    .frame(width: 10, height: 10)
                    .padding(.top, 4)
                if !isLast {
                    Rectangle()
                        .fill(Color.blue.opacity(0.3))
                        .frame(width: 2)
                        .frame(maxHeight: .infinity)
                }
            }
            .frame(width: 12)

            // Content
            VStack(alignment: .leading, spacing: 4) {
                // Travel from previous
                if visit.travelTimeFromPrev > 0 {
                    HStack(spacing: 4) {
                        Image(systemName: "car")
                            .font(.caption2)
                        Text("\(visit.travelTimeFromPrev) min drive")
                            .font(.caption2)
                        if let mi = visit.travelDistanceMiFromPrev {
                            Text("(\(String(format: "%.1f", mi)) mi)")
                                .font(.caption2)
                        }
                    }
                    .foregroundStyle(.secondary)
                    .padding(.bottom, 2)
                }

                // Visit block
                VStack(alignment: .leading, spacing: 2) {
                    Text(client?.name ?? "Unknown Client")
                        .font(.subheadline.weight(.medium))
                    Text("\(visit.startTime.formatted12h) – \(visit.endTime.formatted12h)")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    if let addr = client?.address, !addr.isEmpty {
                        Text(addr)
                            .font(.caption2)
                            .foregroundStyle(.tertiary)
                            .lineLimit(1)
                    }
                }
                .padding(10)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color(.secondarySystemBackground))
                .clipShape(RoundedRectangle(cornerRadius: 8))
                .padding(.bottom, isLast ? 0 : 8)
            }
        }
        .padding(.top, visit.travelTimeFromPrev > 0 ? 4 : 12)
    }
}
